import { Image, Platform } from 'react-native';
import { generatePDF } from 'react-native-html-to-pdf';
import ReactNativeBlobUtil from 'react-native-blob-util';

const logoSource = Image.resolveAssetSource(
  require('../assets/pehra-logo.png'),
);
const logoUri = logoSource?.uri;

const escapeHtml = value =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');

const normalizeLogoUri = uri => {
  if (typeof uri !== 'string') {
    return null;
  }

  const value = uri.trim();
  if (!value || /(null|undefined)/i.test(value)) {
    return null;
  }

  if (
    value.startsWith('http://') ||
    value.startsWith('https://') ||
    value.startsWith('file://') ||
    value.startsWith('content://') ||
    value.startsWith('data:')
  ) {
    return value;
  }

  return null;
};

const getFallbackWatermarkSvg = () => {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="260" height="260" viewBox="0 0 260 260">
      <circle cx="130" cy="130" r="118" fill="#e0edff" stroke="#1d4ed8" stroke-width="4"/>
      <circle cx="130" cy="130" r="96" fill="#f8fbff" stroke="#1d4ed8" stroke-width="2"/>
      <text x="130" y="152" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="96" font-weight="700" fill="#1d4ed8">P</text>
      <text x="130" y="206" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="22" letter-spacing="4" fill="#1d4ed8">PEHRA</text>
    </svg>
  `;

  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
};

export const getPdfWatermarkMarkup = (providedLogoUri = logoUri) => {
  const safeLogoUri =
    normalizeLogoUri(providedLogoUri) || getFallbackWatermarkSvg();

  return `<div class="watermark"><img src="${escapeHtml(
    safeLogoUri,
  )}" /></div>`;
};

export async function downloadTablePdf({
  title,
  subtitle,
  columns,
  rows,
  fileName,
}) {
  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          @page { margin: 42px 34px 40px; }
          * { box-sizing: border-box; }
          body { color: #172033; font-family: Helvetica, Arial, sans-serif; margin: 0; }
          .header { border-bottom: 4px solid #1d4ed8; padding-bottom: 16px; }
          .brand { color: #1d4ed8; font-size: 12px; font-weight: bold; letter-spacing: 2px; }
          h1 { font-size: 24px; margin: 8px 0 4px; }
          .subtitle { color: #6b7280; font-size: 11px; }
          .watermark { left: 0; opacity: 0.055; position: fixed; right: 0; text-align: center; top: 31%; }
          .watermark img { border: 2px solid #1d4ed8; border-radius: 50%; height: 260px; object-fit: cover; width: 260px; }
          table { border-collapse: collapse; margin-top: 24px; position: relative; width: 100%; }
          th { background: #1d4ed8; color: #fff; font-size: 9px; padding: 9px 7px; text-align: left; }
          td { border-bottom: 1px solid #e5e7eb; font-size: 9px; padding: 9px 7px; vertical-align: top; }
          tr:nth-child(even) td { background: #f7f9fc; }
          .footer { color: #6b7280; font-size: 9px; margin-top: 22px; }
        </style>
      </head>
      <body>
        ${getPdfWatermarkMarkup()}
        <div class="header">
          <div class="brand">PEHRA VEHICLE NETWORK</div>
          <h1>${escapeHtml(title)}</h1>
          <div class="subtitle">${escapeHtml(subtitle)} | ${
    rows.length
  } record${rows.length === 1 ? '' : 's'}</div>
        </div>
        <table>
          <thead><tr>${columns
            .map(column => `<th>${escapeHtml(column)}</th>`)
            .join('')}</tr></thead>
          <tbody>
            ${rows
              .map(
                row =>
                  `<tr>${row
                    .map(value => `<td>${escapeHtml(value)}</td>`)
                    .join('')}</tr>`,
              )
              .join('')}
          </tbody>
        </table>
        <div class="footer">Generated by Pehra • Confidential record</div>
      </body>
    </html>`;

  const pdf = await generatePDF({
    html,
    fileName: fileName.replace(/[^a-z0-9-_]/gi, '-'),
    directory: 'Documents',
  });

  const filePath = pdf?.filePath;
  if (!filePath) {
    throw new Error('The PDF could not be created.');
  }

  if (Platform.OS === 'android' && Platform.Version >= 29) {
    const safeName = fileName.replace(/[^a-z0-9-_]/gi, '-');
    const publicUri =
      await ReactNativeBlobUtil.MediaCollection.copyToMediaStore(
        {
          name: `${safeName}.pdf`,
          parentFolder: 'Pehra',
          mimeType: 'application/pdf',
        },
        'Download',
        filePath,
      );

    if (!publicUri) {
      throw new Error('The PDF could not be saved to Downloads.');
    }
    return publicUri;
  }

  return filePath;
}
